### ISSUE TITLE
After Installing htseq-clip Can called from terminal

### ISSUE THREAD

**Issue by gnlemusd** [EMBL-Hentze-group/htseq-clip#1]
Thank you very much or maintenance 

This is the error I got when I run 

Traceback (most recent call last):
  File "/home/nicolas/.local/bin/htseq-clip", line 11, in <module>
    sys.exit(main())
  File "/home/nicolas/.local/lib/python3.6/site-packages/clip/command_line.py", line 4, in main
    clip.main()
  File "/home/nicolas/.local/lib/python3.6/site-packages/clip/clip.py", line 136, in main
    subps = parser.add_subparsers(help='Need positional arguments',dest='subparser',required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

Thank you very much I am not an informatician by formation sorry in advance

Best

Nicolas

**Comment by tschwarzl** [comment]
Hi Nicolas,

thanks for reporting this. Could you please describe the exact steps which lead to the error (the commands)?
 
Thank you very much,
Tom

**Comment by sudeepsahadevan** [comment]
Hi Nicolas,

Many thanks for reporting this issue. I've pushed a new version to fix this issue. Please update the version you are using as:
`pip install htseq-clip --upgrade`
