### ISSUE TITLE
Error while trying to run count

### ISSUE THREAD

**Issue by NordinZandhuis** [EMBL-Hentze-group/htseq-clip#10]
Thanks a lot for making this tool available!

I am trying to run the count function, but I run into the following error:

```
[INFO]  run started at 2024-03-20 20:20
 [INFO]  Count crosslink sites
 [INFO]  Annotation file gencode.vM10.annotation.gff3.windows.txt.gz crosslink sites file SRR5335818Aligned.bed output file SRR5335818Aligned_count.txt
Traceback (most recent call last):
  File "/Users/nordin/.pyenv/versions/3.7.17/envs/iCount_project/lib/python3.7/site-packages/clip/clip.py", line 784, in main
    _count(args)
  File "/Users/nordin/.pyenv/versions/3.7.17/envs/iCount_project/lib/python3.7/site-packages/clip/clip.py", line 143, in _count
    countC = countCLIP(args)
  File "/Users/nordin/.pyenv/versions/3.7.17/envs/iCount_project/lib/python3.7/site-packages/clip/countCLIP.py", line 94, in __init__
    self._annotationSanityCheck()
  File "/Users/nordin/.pyenv/versions/3.7.17/envs/iCount_project/lib/python3.7/site-packages/clip/countCLIP.py", line 141, in _annotationSanityCheck
    raise ValueError("BED file line contains more than 9 fields")
ValueError: BED file line contains more than 9 fields
```

As input I am using the bed file that was generating using the extract function. The top 10 entries are like this:

head SRR5335818Aligned.bed
1	3340178	3340179	SRR5335818_BARCODE_ATCG_UMI_GACCACTCTT|25	1	-
1	4129998	4129999	SRR5335818_BARCODE_ATCG_UMI_TTGCTCTCCT|24	1	+
1	4599340	4599341	SRR5335818_BARCODE_ATCG_UMI_TTATTTTCAT|61	1	+
1	4599341	4599342	SRR5335818_BARCODE_ATCG_UMI_TCTGCGACAC|61	1	+
1	4777581	4777582	SRR5335818_BARCODE_ATCG_UMI_ATCGTGCCCT|28	1	+
1	4793900	4793901	SRR5335818_BARCODE_ATCG_UMI_ACATACCTCC|35	1	-
1	4825254	4825255	SRR5335818_BARCODE_ATCG_UMI_GGTATACCTA|36	1	-
1	4825358	4825359	SRR5335818_BARCODE_ATCG_UMI_CTTTTTCCAC|23	1	-
1	4827099	4827100	SRR5335818_BARCODE_ATCG_UMI_TACGCACCCA|31	1	-
1	4832471	4832472	SRR5335818_BARCODE_ATCG_UMI_GCTGTAGTTT|42	1	-

Any help would be greatly appreciated!

Nordin

**Comment by sudeepsahadevan** [comment]
Hi,
Thanks for giving htseq-clip a try. The error message is about the annotation file. Could you also post a couple of lines from the flattened annotation file `gencode.vM10.annotation.gff3.windows.txt.gz` ?

**Comment by NordinZandhuis** [comment]
Many thanks for the quick response.

```
gzip -dc gencode.vM10.annotation.gff3.windows.txt.gz | head -n 20
unique_id	chromosome	begin	end	strand	gene_id	gene_name	gene_type	gene_region	Nr_of_region	Total_nr_of_region	window_number
ENSMUSG00000102693.1:exon0001W00001	chr1	3073252	3073302	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	1
ENSMUSG00000102693.1:exon0001W00002	chr1	3073272	3073322	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	2
ENSMUSG00000102693.1:exon0001W00003	chr1	3073292	3073342	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	3
ENSMUSG00000102693.1:exon0001W00004	chr1	3073312	3073362	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	4
ENSMUSG00000102693.1:exon0001W00005	chr1	3073332	3073382	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	5
ENSMUSG00000102693.1:exon0001W00006	chr1	3073352	3073402	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	6
ENSMUSG00000102693.1:exon0001W00007	chr1	3073372	3073422	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	7
ENSMUSG00000102693.1:exon0001W00008	chr1	3073392	3073442	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	8
ENSMUSG00000102693.1:exon0001W00009	chr1	3073412	3073462	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	9
ENSMUSG00000102693.1:exon0001W00010	chr1	3073432	3073482	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	10
ENSMUSG00000102693.1:exon0001W00011	chr1	3073452	3073502	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	11
ENSMUSG00000102693.1:exon0001W00012	chr1	3073472	3073522	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	12
ENSMUSG00000102693.1:exon0001W00013	chr1	3073492	3073542	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	13
ENSMUSG00000102693.1:exon0001W00014	chr1	3073512	3073562	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	14
ENSMUSG00000102693.1:exon0001W00015	chr1	3073532	3073582	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	15
ENSMUSG00000102693.1:exon0001W00016	chr1	3073552	3073602	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	16
ENSMUSG00000102693.1:exon0001W00017	chr1	3073572	3073622	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	17
ENSMUSG00000102693.1:exon0001W00018	chr1	3073592	3073642	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	18
ENSMUSG00000102693.1:exon0001W00019	chr1	3073612	3073662	+	ENSMUSG00000102693.1	4933401J01Rik	TEC	exon	1	1	19
```

**Comment by sudeepsahadevan** [comment]
hi thanks!
that is not the correct annotation for the `count` function. Here the function expects the output from `htseq-clip createSlidingWindows` as the input annotation file

Hope this helps!

**Comment by NordinZandhuis** [comment]
My apologies for my ignorance, this was indeed the issue!

Thanks for the help!
