### ISSUE TITLE
Issue in extraction step

### ISSUE THREAD

**Issue by jenc42** [EMBL-Hentze-group/htseq-clip#6]
The .bam files ENCFF218ZEI, ENCFF511HSJ, ENCFF879UID are in my 'bam' solder in SLBP_analysis.
When I try to run command
```
htseq-clip extract -i bam/ENCFF218ZEI.bam -e 2 -s s -g -1 --primary -o sites/ENCFF218ZEI.bed
``` 
after successfully doing

```
cd /path/to/SLBP_analysis
```

This error message occurs:

```
[INFO]  run started at 2022-03-23 13:12
 [INFO]  Extracting start sites
 [INFO]  Bam file : bam/ENCFF218ZEI.bam, output file: sites/ENCFF218ZEI.bed, offset: -1
 [INFO]  Using sites/3jgbrnwq as tmp folder
[E::idx_find_and_load] Could not retrieve index file for 'bam/ENCFF218ZEI.bam'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clip/clip.py", line 257, in main
    _extract(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clip/clip.py", line 71, in _extract
    with bamCLIP(args) as bh:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clip/bamCLIP.py", line 48, in __enter__
    self._bam_checker() # find all chromosomes in the given bam file
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clip/bamCLIP.py", line 86, in _bam_checker
    with pysam.AlignmentFile(self.fInput,mode='rb',check_sq=True,check_header=True,require_index=True) as _bh:
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 1016, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] No such file or directory
```

Do you have any advice? Thanks

**Comment by sudeepsahadevan** [comment]
Please make sure that the bam files are co-ordinate sorted and indexed. This will fix the problem.

**Comment by jenc42** [comment]
thank you, how do you do that?

**Comment by sudeepsahadevan** [comment]
If you don't already have, then install a recent version of [samtools](https://www.htslib.org/doc/samtools.html) then follow the well detailed documentation:
[samtools sort](https://www.htslib.org/doc/samtools-sort.html)
[samtools index](https://www.htslib.org/doc/samtools-index.html)
Most likely the bam files are alreay co-ordinate sorted, and you just need to index it.
You can check the "sorting type" by:
[`samtools view -H <input.bam>`](https://www.htslib.org/doc/samtools-view.html) and checking the first line of the output, it should end with `SO:coordinate` if the file is co-ordinate sorted.
